room14_02:
  hosts:

    # (change IP and interface as needed)
    avisi_pi:
      ansible_host: fe80::cc80:d3ff:d905:6ce7%enx606d3cf84048
      ansible_user: colossuspi

    
    # VM for testing purposes:
    # pi01:
    #   ansible_host: 127.0.0.1
    #   ansible_port: 2222
    #   ansible_user: pi1


floor14:
  children:
    room14_02:

bakeryPis:
  children:
    floor14:

