- name: Provision Pi's
  vars:
    skipSteps: false
  hosts: bakeryPis
  tasks:
  - name: Ping Pi's
    ansible.builtin.ping:
    when: not skipSteps
  
  - name: Install browser
    ansible.builtin.apt:
      name: chromium-browser
    when: not skipSteps

  - name: Install Python
    ansible.builtin.apt:
      name: python3=3.11.*
    when: not skipSteps
    become: true

  - name: Install Python pip websocket library
    ansible.builtin.pip:
      name: websocket-client==1.2.0
      virtualenv: /home/colossuspi/Documents/pythonVenv/
      virtualenv_command: "python3 -m venv"
    
  - name: Copy Python listener script to Pi
    copy:
      src: ../python/
      dest: ./Documents/python/
    # when: not skipSteps
    become: true

  - name: Copy service file for listener script to Pi
    copy:
      src: ./listenerScript.service
      dest: /etc/systemd/system/listenerScript.service
    # when: not skipSteps
    become: true
  
  - name: Copy Environment variables file for listener script to Pi
    copy:
      src: ./envVars
      dest: /etc/systemd/system/envVars
    # when: not skipSteps
    become: true

  - name: Make Python script executable
    command: chmod +x ./Documents/python/main.py
    become: true

  - name: Enable and (re-)start Python listener script service and daemon_reload
    ansible.builtin.systemd_service:
      enabled: true
      state: restarted
      daemon_reload: true
      name: listenerScript.service
    become: true
  
